apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: route53dynip
spec:
  selector:
    matchLabels:
      app: route53dynip
  replicas: 1
  template:
    metadata:
      labels:
        app: route53dynip
    spec:
      containers:
      - name: route53dynip
        image: jburks725/route53dynip:5
        args: [ "{{vpn.YOURNAMEHERE.com}}" ]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: route53credentials
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: route53credentials
                key: secretKey